apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    shareName: myshare
    readOnly: false
  claimRef:
    kind: PersistentVolumeClaim
    name: cms-pvc
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  volumeMode: Filesystem
