apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    shareName: myshare
    readOnly: false
  claimRef:
    kind: PersistentVolumeClaim
    name: mongodb-pvc
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  volumeMode: Filesystem